Repository button-inc/emissions-elt-demo, pull requests merged in 2022-12, with the labels that each got.

#111 chore: sample insights data
  .gitignore
  app/package.json
  app/scripts/generate-insights-data.mjs
  app/yarn.lock
  jsonschema/destination-api.schema.json
Labels: feature

#116 chore: added back buttons to some frontend components
  app/pages/admin.tsx
  app/pages/home.tsx
  app/pages/import.tsx
  app/pages/insights.tsx
  app/pages/login.tsx
  app/pages/view.tsx
Labels: development

#117 fix: use single default layout in app
  app/pages/_app.tsx
  app/pages/admin.tsx
  app/pages/home.tsx
  app/pages/import.tsx
  app/pages/insights.tsx
  app/pages/login.tsx
  app/pages/view.tsx
  app/styles/globals.css
Labels: bug

#119 fix: use single default layout in app
  app/pages/_app.tsx
  app/pages/admin.tsx
  app/pages/home.tsx
  app/pages/import.tsx
  app/pages/insights.tsx
  app/pages/login.tsx
  app/pages/view.tsx
  app/styles/globals.css
Labels: bug, enhancement

#118 fix: change pre-commit to run prettier locally on commit
  .pre-commit-config.yaml
  .tool-versions
  README.md
Labels: bug, code improvement
