Repository button-inc/emissions-elt-demo, pull requests merged in 2023-02, with the labels that each got.

#196 chore: load insights dataset with data clean room
  dags/insights-db-ingestion-dag.py
  dags/sample-building-ingestion-dag.py
  dags/sample-waste-data-ingestion-dag.py
  schema/deploy/tables/raw_insights.sql
  schema/revert/tables/insight-destination-processed@alpha-23-01-18.sql
  schema/revert/tables/raw_insights.sql
  schema/sqitch.plan
  schema/verify/tables/raw_insights.sql
Labels: development

#206 feat: use google dlp to analyze for pii in tables
  dags/insights-db-ingestion-dag.py
  dags/sample-building-ingestion-dag.py
  dags/sample-waste-data-ingestion-dag.py
  schema/deploy/tables/dlp_analytics.sql
  schema/revert/tables/dlp_analytics.sql
  schema/sqitch.plan
  schema/verify/tables/dlp_analytics.sql
Labels: enhancement

#209 fix: correct non-functioning GCP DAGs
  dags/insights-db-ingestion-dag.py
  dags/sample-building-ingestion-dag.py
  dags/sample-waste-data-ingestion-dag.py
Labels: bug

#215 214-telus-docs
  app/README.md
  app/app/[lng]/analyst/analytic/page.tsx
  app/app/[lng]/analyst/anonymized/[id]/page.tsx
  app/app/[lng]/analyst/anonymized/page.tsx
  app/app/[lng]/analyst/dataset/available/page.tsx
  app/app/[lng]/analyst/dataset/connection/page.tsx
  app/app/[lng]/analyst/home/page.tsx
  app/app/[lng]/analyst/imported/[id]/page.tsx
  app/app/[lng]/analyst/imported/page.tsx
  app/app/[lng]/analyst/insight/page.tsx
  app/app/components/query/DataSetQuery.tsx
  app/app/components/route/Analytic.tsx
  app/app/components/route/Home.tsx
  app/app/components/route/Insight.tsx
  app/app/components/route/anonymized/Anonymized.tsx
  app/app/components/route/anonymized/id/Area.tsx
  app/app/components/route/dataset/Available.tsx
  app/app/components/route/dataset/Config.tsx
  app/app/components/route/dataset/connection/Add.tsx
  app/app/components/route/dataset/connection/Connection.tsx
  app/app/components/route/dataset/connection/Container.tsx
  app/app/components/route/imported/Imported.tsx
  app/app/components/route/imported/id/Area.tsx
Labels: documentation
