Repository button-inc/emissions-elt-demo, pull requests merged in 2023-01, with the labels that each got.

#123 chore: added sqitch schemas for users and roles
  schema/deploy/add_table.sql
  schema/deploy/add_test_user.sql
  schema/deploy/change_password.sql
  schema/deploy/create-roles.sql
  schema/deploy/insert_user.sql
  schema/deploy/users.sql
  schema/deploy/verify_grant.sql
  schema/revert/add_table.sql
  schema/revert/add_test_user.sql
  schema/revert/change_password.sql
  schema/revert/insert_user.sql
  schema/revert/users.sql
  schema/revert/verify_grant.sql
  schema/sqitch.conf
  schema/sqitch.plan
  schema/verify/add_table.sql
  schema/verify/add_test_user.sql
  schema/verify/change_password.sql
  schema/verify/insert_user.sql
  schema/verify/users.sql
  schema/verify/verify_grant.sql
Labels: development

#134 fix: remove extra spaces from template (pre-commit error)
  .github/ISSUE_TEMPLATE/user_story_template.md
Labels: bug

#132 feat: Insights ingestion tables
  schema/deploy/tables/import_record.sql
  schema/deploy/tables/insight-destination-processed.sql
  schema/revert/tables/import_record.sql
  schema/revert/tables/insight-destination-processed.sql
  schema/sqitch.plan
  schema/verify/tables/import_record.sql
  schema/verify/tables/insight-destination-processed.sql
Labels: enhancement

#140 chore: add sqitch plan for PostGIS extension
  schema/deploy/postgis_extension.sql
  schema/revert/postgis_extension.sql
  schema/sqitch.plan
  schema/verify/postgis_extension.sql
Labels: feature, development

#147 chore: added data schemas and role permissions
  schema/deploy/add_data_schemas.sql
  schema/deploy/create-roles.sql
  schema/revert/add_data_schemas.sql
  schema/sqitch.plan
  schema/verify/add_data_schemas.sql
Labels: development

#133 feat: insights ingestion dag proof-of-concept
  app/scripts/generate-insights-data.mjs
  dags/insights-db-ingestion-dag.py
  jsonschema/destination-api.schema.json
Labels: enhancement

#160 feat: geospatial data ingestion
  dags/insights-db-ingestion-dag.py
  dags/sample-geospacial-db-ingestion-dag.py
  schema/deploy/tables/import_record.sql
  schema/deploy/tables/insight-destination-processed.sql
  schema/deploy/tables/study_area_geometry.sql
  schema/revert/tables/study_area_geometry.sql
  schema/sqitch.plan
  schema/verify/tables/study_area_geometry.sql
Labels: enhancement

#162 chore: add ids in two forms to insights_voyage table
  schema/deploy/computed_columns/voyage_combined_id.sql
  schema/deploy/tables/add_id_to_insights_voyage.sql
  schema/revert/computed_columns/voyage_combined_id.sql
  schema/revert/tables/add_id_to_insights_voyage.sql
  schema/sqitch.plan
  schema/verify/computed_columns/voyage_combined_id.sql
  schema/verify/tables/add_id_to_insights_voyage.sql
Labels: enhancement, development

#159 feat: analytics screen
  app/app/[lng]/analyst/analytic/page.tsx
  app/app/components/DefaultLayout.tsx
  app/app/components/layout/Spinner.jsx
  app/app/i18n/locales/en/analytic/page.json
  app/app/i18n/locales/fr/analytic/page.json
  app/app/styles/globals.css
Labels: development

#193 feat!: replace analytics page with metabase embeded iframe
  app/app/[lng]/analyst/analytic/page.tsx
Labels: enhancement, feature
